#!/bin/bash -e
xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/cloud/prisma/secops.yaml
xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/cloud/prisma/ntp.yaml
xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/cloud/prisma/metadataapi.yaml
