#!/bin/bash -e

function main() {
  rc=0
  ns="memphis"

  kubectl get ns $ns > /dev/null 2>&1 && {
    err "Deleting Kubernetes Namespace $ns"
    kubectl delete ns $ns || rc=3
  } || {
    err "Kubernetes Namespace $ns does not exist"
  }

  id=$(/Users/jscott/workspace/k8s-simple-apps/tennessee/bin/scripts/xapoctl api list namespaces -n "/806775361903163392/jody/ek1-us-east-2-eksctl-io" -f "name==/806775361903163392/jody/ek1-us-east-2-eksctl-io/memphis" | /Users/jscott/workspace/k8s-simple-apps/tennessee/bin/darwin/x86_64/jq -r '.[].ID')
  [[ "$id" ]] && {
    err "Deleting Prisma Namespace $ns with id $id"
    apoctl api delete namespace "/806775361903163392/jody/ek1-us-east-2-eksctl-io/memphis" || rc=3
  } || {
    err "Prisma Namespace $ns does not exist"
  }
  return "$rc"
}

function err() { echo "$@" 1>&2; }

main "$@"

