#!/bin/bash -e
cd "$(dirname "$0")"
kubectl apply -f /Users/jscott/workspace/k8s-simple-apps/tennessee/knoxville/k8s/ns.yaml
sleep 2
kubectl apply -f /Users/jscott/workspace/k8s-simple-apps/tennessee/knoxville/k8s
xapoctl api import -n "/806775361903163392/jody/ek1-us-east-2-eksctl-io/knoxville" --file "/Users/jscott/workspace/k8s-simple-apps/tennessee/knoxville"/prisma/config.yaml
