#!/bin/bash

NAMESPACE="memphis"
SELECTOR_FILTER="app=frontend,sim-cloud=AWS,sim-region=us-east-1,sim-account=10"

function main() {
  cd "$(dirname "$0")" || { err "Unable to determine working directory"; return 3; }
  [ -f script ] || { err "Missing file script"; return 3; }
  local pod
  pod=$(kubectl get pods -n "$NAMESPACE" --selector "$SELECTOR_FILTER" -o=jsonpath="{.items[*]['metadata.name']}")
  [[ "$pod" ]] || { err "Unable to find pod"; return 3; }

  kubectl -n "$NAMESPACE" cp script "$pod":/tmp/inject || { err "Failed"; return 3; }
  kubectl exec -it -n "$NAMESPACE" "$pod" -- bash /tmp/inject
}

function err() { echo "$@" 1>&2; }

main "$@"
