#!/bin/bash -e
apoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/group/prisma/dns.yaml
apoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/group/prisma/nodes.yaml
