#!/bin/bash -e
/Users/jscott/workspace/k8s-simple-apps/tennessee/bin/scripts/xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/group/prisma/dns.yaml
/Users/jscott/workspace/k8s-simple-apps/tennessee/bin/scripts/xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/group/prisma/nodes.yaml
/Users/jscott/workspace/k8s-simple-apps/tennessee/bin/scripts/xapoctl api import -n /806775361903163392/jody/ek1-us-east-2-eksctl-io --file /Users/jscott/workspace/k8s-simple-apps/tennessee/group/prisma/kubeapi.yaml
