#!/bin/bash -e
cd "$(dirname "$0")"
kubectl apply -f /Users/jscott/workspace/k8s-simple-apps/tennessee/nashville/k8s/ns.yaml
sleep 2
kubectl apply -f /Users/jscott/workspace/k8s-simple-apps/tennessee/nashville/k8s
apoctl api import -n "/806775361903163392/jody/ek1-us-east-2-eksctl-io/nashville" --file prisma/config.yaml
